### Search Subreddits
GET https://www.reddit.com/search.json?q=ana&type=sr%2Cuser HTTP/1.1

### Get Subreddit posts
GET http://www.reddit.com/r/ama/top.json?t=all HTTP/1.1

### Get post comments
GET https://www.reddit.com/r/AMA/comments/hl7j7x/im_going_to_do_an_ama_that_will_only_have_me_so/.json HTTP/1.1

